using System;
using System.Security.Cryptography;
using System.Text;

namespace Yonderfix.web.Helpers
{
    public static class PkceUtil
    {
        /// <summary>
        /// Generates a cryptographically secure code verifier.
        /// </summary>
        /// <returns>A URL-safe base64 encoded string used as the code verifier.</returns>
        public static string GenerateCodeVerifier()
        {
            // Create a 32-byte random sequence
            using (var rng = RandomNumberGenerator.Create())
            {
                var bytes = new byte[32];
                rng.GetBytes(bytes);
                return Base64UrlEncode(bytes);
            }
        }

        /// <summary>
        /// Generates the code challenge using the S256 transformation method.
        /// </summary>
        /// <param name="codeVerifier">The code verifier generated by GenerateCodeVerifier().</param>
        /// <returns>A URL-safe base64 encoded string used as the code challenge.</returns>
        public static string GenerateCodeChallenge(string codeVerifier)
        {
            using (var sha256 = SHA256.Create())
            {
                var bytes = Encoding.ASCII.GetBytes(codeVerifier);
                var hash = sha256.ComputeHash(bytes);
                return Base64UrlEncode(hash);
            }
        }

        /// <summary>
        /// Encodes the provided byte array using URL-safe Base64 encoding.
        /// </summary>
        private static string Base64UrlEncode(byte[] input)
        {
            return Convert.ToBase64String(input)
                .Replace("+", "-")
                .Replace("/", "_")
                .Replace("=", "");
        }
    }
}
